language: objective-c
osx_image: xcode10.3
branches:
  only:
    - master
    - develop
    - /^feature-.*$/
matrix:
  include:
    - env: SCHEME="TheStories"
    - env: SCHEME="TheStoriesDev"
script:
  - xcodebuild -workspace "TheStories.xcworkspace" -scheme ${SCHEME} -sdk iphonesimulator12.4 -destination 'platform=iOS Simulator,name=iPhone X,OS=12.4' build
before_install:
  - pod install