default_platform(:ios)

platform :ios do
  desc "Swiftlint"
  lane :lint do
    swiftlint(mode: :lint, 
              config_file: ".swiftlint.yml", 
              ignore_exit_status: false
    )
  end

  desc "Build app"
  lane :build do
    xcodebuild(
               scheme: "TheStories",
               workspace: "TheStories.xcworkspace",
               configuration: "Debug",
               sdk: "iphonesimulator",
               destination: "platform=iOS Simulator,OS=12.2,name=iPhone 6",
               build: true
    )
  end

  desc "Run test"
  lane :test do
    scan(
         workspace: "TheStories.xcworkspace",
         devices: "iPhone 6",
         scheme: "TheStories",
         clean: true,
         code_coverage: true
  )
  end
end
